apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - ../../0.1.0.100/base
configMapGenerator:
  - name: configurations-configmap
    files:
      - config/config-schema.json
      - config/config.json
      - config/menu-config-schema.json
      - config/menu-config.json
      - config/secrets-schema.json
      - config/secrets.json
images:
  - name: acrsaaseswesteuropedev.azurecr.io/platform-management
    newName: acrsaaseswesteuropedev.azurecr.io/platform-management
    newTag: 0.1.0.100
