apiVersion: v1
kind: Service
metadata:
  name: data-management-api
  labels:
    app: data-management-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: data-management-api