apiVersion: v1
kind: Service
metadata:
  name: platform-management
  labels:
    app: platform-management
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: platform-management