apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  labels:
    app: postgres
data:
  url: jdbc:postgresql://postgres:5432/postgres
  SONAR_SEARCH_JAVAADDITIONALOPTS: -Dnode.store.allow_mmap=false

