log:
  level: debug
  format: json

serve:
  proxy:
    port: 4455
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      debug: true
  api:
    port: 4456

errors:
  fallback:
    - json
  handlers:
    redirect:
      enabled: true
      config:
        to: https://bizerba-bss-devops.com/login
        when:
          -
            error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html
    json:
      enabled: true
      config:
        verbose: true

access_rules:
  #matching_strategy: glob
  repositories:
  - file:///etc/rules/access-rules.yaml

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
  jwt:
    enabled: true
    config:
      jwks_urls:
        - https://bizerbab2cdev.b2clogin.com/bizerbab2cdev.onmicrosoft.com/b2c_1a_signup_signin2_es/discovery/v2.0/keys
      trusted_issuers:
        - https://bizerbab2cdev.b2clogin.com/ac5b6968-1018-4727-b694-1a7c84a2ac90/v2.0/
      target_audience:
        - 4ec6773c-44a3-4d10-baf2-610273644e22
      allowed_algorithms:
        - RS256
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true

mutators:
  noop:
    enabled: true
