apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../RC-0.2.0.1/base
configMapGenerator:
- name: configurations-configmap
  files:
  - appsettings.json
  - appsettings.QA.json
images:
  - name: acrsaaseswesteuropedev.azurecr.io/organizationalstructuremanagement-api
    newName: acrsaaseswesteuropedev.azurecr.io/organizationalstructuremanagement-api
    newTag: RC-0.2.0.1