apiVersion: v1
kind: Service
metadata:
  name: organizationalstructuremanagement-api
  labels:
    app: organizationalstructuremanagement-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: organizationalstructuremanagement-api