apiVersion: v1
kind: Service
metadata:
  name: tenant-management
  labels:
    app: tenant-management
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: tenant-management