apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
configMapGenerator:
  - name: configurations-configmap
    files:
    - appsettings.json
    - appsettings.QA.json
images:
  - name: acrsaaseswesteuropedev.azurecr.io/data-management-api
    newName: acrsaaseswesteuropedev.azurecr.io/data-management-api
    newTag: RC-0.1.0.0
