apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-platform-mastertenantmanagement-api
  labels:
    app: saas-platform-mastertenantmanagement-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-platform-mastertenantmanagement-api
  template:
    metadata:
      labels:
        app: saas-platform-mastertenantmanagement-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: saas-platform-mastertenantmanagement-api
                topologyKey: "kubernetes.io/hostname"              
      containers:
          - name: saas-platform-mastertenantmanagement-api
            image: acrsaaseswesteuropedev.azurecr.io/saas-platform-mastertenantmanagement-api:RC-0.3.0.22  
            env:
              - name: ASPNETCORE_URLS
                value: "http://+:80"
              - name: ASPNETCORE_ENVIRONMENT
                value: "Development"  
            ports:
              - name: http
                containerPort: 80
            volumeMounts:
              - name: config
                mountPath: /app/Configuration
            resources: {}      
      volumes:
      - name: config
        configMap:
          name: configurations-configmap    
      restartPolicy: Always