apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "kv-saas-westeurope-dev"
  - name: azureTenantId
    value: "xxxxxxxx"
  - name: azureClientId
    value: "xxxxxxxx"
auth:
  secretStore: kubernetes
