- id: 'biss-authn:api:login'
  upstream:
    preserve_host: true
    url: 'http://biss-authn:8090'
  match:
    url: 'https://bizerba-bss-dev.com/login'
    methods:
      - GET
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: json

- id: 'biss-authn:api:gettoken'
  upstream:
    preserve_host: true
    url: 'http://biss-authn:8090'
  match:
    url: 'https://bizerba-bss-dev.com/gettoken<.*>'
    methods:
      - GET
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'biss-authn:api:logout'
  upstream:
    preserve_host: true
    url: 'http://biss-authn:8090'
  match:
    url: 'https://bizerba-bss-dev.com/logout'
    methods:
      - GET
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'dev-domain:web:protected'
  upstream:
    preserve_host: true
    url: 'http://platform-management'
    # strip_path: '/bizerba-management-platform'
  match:
    url: 'https://bizerba-bss-dev.com/'
    methods:
      - GET
      - POST
  authenticators:
    - handler: jwt
      config:
        token_from:
          cookie: auth-token
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'tenant:web:protected'
  upstream:
    preserve_host: true
    url: 'http://tenant-management'
    strip_path: '/tenant-management'
  match:
    url: 'https://bizerba-bss-dev.com/tenant-management<.*>'
    methods:
      - GET
      - POST
  authenticators:
    - handler: jwt
      config:
        token_from:
          cookie: auth-token
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'platform-management:web:protected'
  upstream:
    preserve_host: true
    url: 'http://platform-management'
    strip_path: '/bizerba-management-platform'
  match:
    url: 'https://bizerba-bss-dev.com/bizerba-management-platform<.*>'
    methods:
      - GET
      - POST
  authenticators:
    - handler: jwt
      config:
        token_from:
          cookie: auth-token
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'mastertenant:api:protected'
  upstream:
    preserve_host: true
    url: 'http://mtm-api'
    strip_path: '/mastertenant'
  match:
    url: 'https://bizerba-bss-dev.com/mastertenant/<.*>'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: jwt
      config:
        token_from:
          cookie: auth-token
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'notification:hub:protected'
  upstream:
    preserve_host: true
    url: 'http://saas-platform-notificationservice'
    strip_path: '/notificationHub'
  match:
    url: 'https://bizerba-bss-dev.com/notificationHub<.*>'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: jwt
      config:
        token_from:
          cookie: auth-token
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'organizationalstructure:api:protected'
  upstream:
    preserve_host: true
    url: 'http://organizationalstructuremanagement-api'
    strip_path: '/organizationalstructure'
  match:
    url: 'https://bizerba-bss-dev.com/organizationalstructure/<.*>'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: jwt
      config:
        token_from:
          cookie: auth-token
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'poc-poolconnections:api:protected'
  upstream:
    preserve_host: true
    url: 'http://poc-poolconnections-api'
    strip_path: '/poc-poolconnections'
  match:
    url: 'https://bizerba-bss-dev.com/poc-poolconnections<.*>'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: jwt
      config:
        token_from:
          cookie: auth-token
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'labelmanagement:api:protected'
  upstream:
    preserve_host: true
    url: 'http://label-management-api'
    strip_path: '/label-management'
  match:
    url: 'https://bizerba-bss-dev.com/label-management/<.*>'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: jwt
      config:
        token_from:
          cookie: auth-token
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect

- id: 'datamanagement:api:protected'
  upstream:
    preserve_host: true
    url: 'http://data-management-api'
    strip_path: '/data-management'
  match:
    url: 'https://bizerba-bss-dev.com/data-management/<.*>'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: jwt
      config:
        token_from:
          cookie: auth-token
  mutators:
    - handler: noop
  authorizer:
    handler: allow
  errors:
    - handler: redirect