apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtm-api
  labels:
    app: mtm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtm-api
  template:
    metadata:
      labels:
        app: mtm-api
      annotations:
        dapr.io/app-id: mtm-api
        dapr.io/enabled: 'true'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: mtm-api
                topologyKey: "kubernetes.io/hostname"              
      containers:
          - name: mtm-api
            image: acrsaaseswesteuropedev.azurecr.io/saas-platform-mastertenantmanagement-api:RC-0.4.0.1
            readinessProbe:
              httpGet:
                path: /health/ready
                port: 80
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /health/live
                port: 80
              initialDelaySeconds: 15
              periodSeconds: 20
            env:
              - name: ASPNETCORE_URLS
                value: "http://+:80"
              - name: ASPNETCORE_ENVIRONMENT
                value: "Development"  
            ports:
              - name: http
                containerPort: 80
            volumeMounts:
              - name: config
                mountPath: /app/Configuration
            resources: {}      
      volumes:
      - name: config
        configMap:
          name: configurations-configmap 
      - name: certificate
        configMap:
          name: certificate-configmap          
      restartPolicy: Always