apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../RC-0.1.3.1/base
configMapGenerator:
  - name: configurations-configmap
    files:
    - appsettings.json
    - appsettings.Development.json
images:
  - name: acrsaaseswesteuropedev.azurecr.io/labelmanagement-api
    newName: acrsaaseswesteuropedev.azurecr.io/labelmanagement-api
    newTag: RC-0.1.3.1
